import { IH21Column } from 'h21-be-ui-kit';

export const columnsConst: IH21Column[] = [
  // {
  //   caption: 'Selected',
  //   name: 'selected',
  //   required: false,
  //   default: true,
  //   displayed: true,
  //   isSystem: true,
  // },
  {
    caption: 'Cancellation policy mark',
    name: 'cancellationMark',
    required: false,
    default: true,
    displayed: true,
    isSystem: true,
  },
  {
    caption: 'Type',
    name: 'typeName',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Order number',
    name: 'viewOrderNumber',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Invoice number',
    name: 'invoiceNumber',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Booking code',
    name: 'bookingCode',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Provider confirmation',
    name: 'providerConfirmation',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Customer',
    name: 'customerName',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Customer company',
    name: 'customerCompanyName',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Booker',
    name: 'bookerId',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Booker email',
    name: 'createUserName',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Company',
    name: 'companyName',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Trip name',
    name: 'tripName',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Receiving',
    name: 'orderPlacedDate',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Arrival',
    name: 'arrivalDate',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Departure',
    name: 'departureDate',
    required: false,
    default: true,
    displayed: true,
  },

  {
    caption: 'Nights',
    name: 'nights',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Order status',
    name: 'orderStateName',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Payment status',
    name: 'paymentStateName',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Order total rate',
    name: 'finalCost',
    required: false,
    default: true,
    displayed: true,
  },
  {
    caption: 'Supplier',
    name: 'providerCode',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Internal tour number',
    name: 'tourOperatorCode',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Internal tour operator',
    name: 'tourOperatorName',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Payment form',
    name: 'paymentForm',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Account number',
    name: 'payAccountNumber',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Horse21pro ID',
    name: 'H21ProLogin',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'PNR',
    name: 'pnr',
    required: false,
    default: false,
    displayed: false,
  },
  {
    caption: 'Actions',
    name: 'actions',
    required: false,
    default: true,
    displayed: true,
    isSystem: true,
  },
];
