export const ProviderLogo = {
  Talixo: './assets/provider-logos/talixo.png',
  HotelBeds: './assets/provider-logos/hotelbeds__tourico.png',
  Expedia: './assets/provider-logos/expedia.png',
  Booking: './assets/provider-logos/booking.png',
  Pegasus: '',
  Tourico: '',
  Gulliver: './assets/provider-logos/GTA.png',
  Travco: './assets/provider-logos/travco.png',
  Hotusa: './assets/provider-logos/hotusa.png',
  Trust: '',
  Miki: '',
  Acase: './assets/provider-logos/acase.png',
  JacTravel: './assets/provider-logos/jacttravel.png',
  DotW: './assets/provider-logos/dotW.png',
  TotalStay: './assets/provider-logos/totalstay.png',
  Veturis: './assets/provider-logos/veturis.png',
  NegoRates: '',
  Orbitz: '',
  Bico: '',
  InterContinental: './assets/provider-logos/intercontinental.png',
  'Negotiated(online)': '',
  Bonotel: './assets/provider-logos/bonotel.png',
  W2M: './assets/provider-logos/w2m.png',
  GoGlobalTravel: './assets/provider-logos/global-travel.png',
  'DHISCO (Negotiated rates)': './assets/provider-logos/dhisco.png',
};
